package:
  name: danpos
  version: 2.2.2

requirements:
  build:
    - python 2.7
    - numpy
    - r-base 
    - rpy2
    - pysnptools
  run:
    - python 2.7
    - numpy
    - r-base
    - rpy2
    - samtools


