{% set name = "Canu" %}
{% set version = "1.7" %}
{% set hash = "c5be54b0ad20729093413e7e722a19637d32e966dc8ecd2b579ba3e4958d378a" %}

package:
  name: '{{ name|lower }}-pbs'
  version: '{{ version }}'
source:
# Canu currently needs to come from git to get its version string right
  fn: '{{ name|lower }}_{{ version }}.tar.gz'
  url: 'https://github.com/marbl/{{ name|lower }}/archive/v{{ version }}.tar.gz'
  sha256: '{{ hash }}'
  patches:
        - canu1.patch

build:
  number: 0
  skip: True  # [osx]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - perl
    - gnuplot >=5.0.5
  run:
    - libgcc   # [not osx]
    - perl
    - perl-filesys-df
    - openjdk
    - gnuplot >=5.0.5

test:
  commands:
    - canu --version

about:
  home: 'http://canu.readthedocs.org/'
  license: 'GPLv2 and others'
  summary: 'This version of canu has been optmized for compatibility with PBS Pro Workload Manager and Job Scheduler used at Imperial College London.'
  Description: |
    'Canu is a fork of the Celera Assembler, designed for high-noise single-molecule sequencing (such as the PacBio RS II/Sequel or Oxford Nanopore MinION).'

extra:
  identifiers:
    - doi:10.1101/gr.215087.116 
