 package:
   name: r-gdal
   version: "1.2_7"

 source:
    url: https://cran.r-project.org/src/contrib/rgdal_1.2-7.tar.gz
    md5: d9c64bd1b5b31e3b4d199fe6aeaacdde
    sha1: 5dc94e2a600d79b8a1b04462e1d4812007ca0bb8
    sha256: f4e4e540cc0c8a85e23c7ed9d869e7b3e8fc5049717e37a7b8d2bdf99b47b953

#   patches:
#     - cx1.patch

 build:
   number: 0
   rpaths:
     - lib/
     - lib/R/lib/

 requirements:
  build:
    - libgdal >=1.6.3
    - r >=3.3.0
    - r-sp >=1.1_0
    - jpeg ==8d
  run:
    - libgdal >=1.6.3
    - r >=3.3.0
    - r-sp >=1.1_0
    - jpeg ==8d

 about:
   home: https://cran.r-project.org/package=rgdal
   license: GPL2,GPL3
