{% set version = '0.5-5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hitandrun
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hitandrun_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hitandrun/hitandrun_{{ version }}.tar.gz
  sha256: a4050e790eac5435f066a20542fd4686b85e9fe98b735d0e7867ebe3cff6eba3

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.8)
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-rcdd >=1.1

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcdd >=1.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('hitandrun')"           # [not win]
    - "\"%R%\" -e \"library('hitandrun')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/gertvv/hitandrun
  license: GPL-3
  summary: The "Hit and Run" Markov Chain Monte Carlo method for sampling uniformly from convex
    shapes defined by linear constraints, and the "Shake and Bake" method for sampling
    from the boundary of such shapes. Includes specialized functions for sampling normalized
    weights with arbitrary linear constraints.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

