 package:
   name: r-lymphclon
   version: "1.3.0"

 source:
    url: https://cran.r-project.org/src/contrib/lymphclon_1.3.0.tar.gz
    md5: 5c4771bc6c2a8af4538dc531038cb51a
    sha1: 9782c466028f1bbd035d6aa5b95efdf636b61d07
    sha256: 80ba1dc0413e6c5fdd21dad8b9a0bb0f8c4906f1bf19f0ea90a167317520daca

 build:
   number: 0
   rpaths:
     - lib/
     - lib/R/lib/

 requirements:
  build:
    - r >=2.15.0
    - r-base
    - gxx_linux-64
    - r-expm
    - r-corpcor
  run:
    - r >=r2.15.0
    - r-base
    - r-expm
    - r-corpcor

 about:
   home: https://cran.r-project.org/web/packages/lymphclon/index.html
   summary: A  clonality score estimator that takes full advantage of the multi-biological-replicate structure of modern sequencing experiments; it specifically takes into account the reality that, typically, the clonal coverage is well below 0.1%.
   license: LGPL-2
