 package:
   name: pycortex
   version: "0.1.1"

 source:
   git_url: https://github.com/gallantlab/pycortex.git
   git_tag: release-0.1.1

 build:
   number: 0

 requirements:
  build:
    - python
    - cython
    - scipy
    - h5py
    - nibabel
    - matplotlib
    - pillow
    - numexpr
    - tornado
    - lxml
    - networkx

  run:
    - python
    - cython
    - scipy
    - h5py
    - nibabel
    - matplotlib
    - pillow
    - numexpr
    - tornado
    - lxml
    - networkx

 about:
   home: https://gallantlab.github.io/
   license: BSD 2-clause
   license_file: LICENSE
