{% set version = '2.0.8' %}
{% set name = 'hypervolume' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name }}
  version: {{ version|replace("-", "_") }}

source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz'
  sha256: 047ddec979e56d98cc479d84f863b341940fe302bd29edd1177dbbc2532f7900

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{native}}toolchain          # [win]
    - {{posix}}filesystem          # [win]
    - {{posix}}make

  host:
    - r-base
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-data.table
    - r-e1071
    - r-fastcluster
    - r-geometry
    - r-hitandrun
    - r-ks
    - r-maps
    - r-mvtnorm
    - r-pdist
    - r-progress
    - r-raster
    - r-rgeos
    - r-rgl
    - r-sp

  run:
    - r-base
    - {{native}}gcc-libs           # [win]
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-data.table
    - r-e1071
    - r-fastcluster
    - r-geometry
    - r-hitandrun
    - r-ks
    - r-maps
    - r-mvtnorm
    - r-pdist
    - r-progress
    - r-raster
    - r-rgeos
    - r-rgl
    - r-sp

test:
  commands:
    - $R -e "library('hypervolume')"           # [not win]
    - "\"%R%\" -e \"library('hypervolume')\""  # [win]

about:
  home: 'https://CRAN.R-project.org/package={{ name }}'
  license: GPL-3
  summary: 'High Dimensional Geometry and Set Operations Using Kernel Density Estimation, Support Vector Machines, and Convex Hulls.'
  description: |
    'Estimates the shape and volume of high-dimensional datasets and performs set operations:
    intersection / overlap, union, unique components, inclusion test, and hole detection.
    Uses stochastic geometry approach to high-dimensional kernel density estimation,
    support vector machine delineation, and convex hull generation. Applications include
    modeling trait and niche hypervolumes and species distribution modeling.'

  license_family: GPL3
