{% set version = '2.0.11' %}
{% set name = 'hypervolume' %}

package:
  name: r-{{ name }}
  version: {{ version|replace("-", "_") }}

source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz'
  sha256: 0cafd5db5e75f1e02dc917682d19da336de5b475c4753bf74f90f93f37d6ddd1

build:
  skip: True      # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

  host:
    - r-base
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-data.table
    - r-e1071
    - r-fastcluster
    - r-geometry
    - r-hitandrun
    - r-ks
    - r-maps
    - r-mvtnorm
    - r-pdist
    - r-progress
    - r-raster
    - r-rgeos
    - r-rgl
    - r-sp

  run:
    - r-base
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-data.table
    - r-e1071
    - r-fastcluster
    - r-geometry
    - r-hitandrun
    - r-ks
    - r-maps
    - r-mvtnorm
    - r-pdist
    - r-progress
    - r-raster
    - r-rgeos
    - r-rgl
    - r-sp

test:
  commands:
    - $R -e "library('hypervolume')"           # [not win]

about:
  home: 'https://CRAN.R-project.org/package={{ name }}'
  license: GPL-3
  summary: 'High Dimensional Geometry and Set Operations Using Kernel Density Estimation, Support Vector Machines, and Convex Hulls.'
  description: |
    'Estimates the shape and volume of high-dimensional datasets and performs set operations:
    intersection / overlap, union, unique components, inclusion test, and hole detection.
    Uses stochastic geometry approach to high-dimensional kernel density estimation,
    support vector machine delineation, and convex hull generation. Applications include
    modeling trait and niche hypervolumes and species distribution modeling.'

  license_family: GPL3
