{% set version = '3.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hypervolume
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hypervolume_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hypervolume/hypervolume_{{ version }}.tar.gz
  sha256: a71e7be660568fe7e8f0783b74041289c07e14f0b512e00a06520ec96c8d950d

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rgl, magick, alphahull, knitr, rmarkdown, gridExtra
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-caret
    - r-data.table
    - r-doparallel
    - r-dplyr
    - r-e1071
    - r-fastcluster
    - r-foreach
    - r-geometry
    - r-ggplot2
    - r-hitandrun
    - r-ks
    - r-maps
    - r-mvtnorm
    - r-palmerpenguins
    - r-pbapply
    - r-pdist
    - r-progress
    - r-purrr
    - r-raster
    - r-rgeos
    - r-sp

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-caret
    - r-data.table
    - r-doparallel
    - r-dplyr
    - r-e1071
    - r-fastcluster
    - r-foreach
    - r-geometry
    - r-ggplot2
    - r-hitandrun
    - r-ks
    - r-maps
    - r-mvtnorm
    - r-palmerpenguins
    - r-pbapply
    - r-pdist
    - r-progress
    - r-purrr
    - r-raster
    - r-rgeos
    - r-sp

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('hypervolume')"           # [not win]
    - "\"%R%\" -e \"library('hypervolume')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=hypervolume
  license: GPL-3
  summary: 'Estimates the shape and volume of high-dimensional datasets and performs set operations:
    intersection / overlap, union, unique components, inclusion test, and hole detection.
    Uses stochastic geometry approach to high-dimensional kernel density estimation,
    support vector machine delineation, and convex hull generation. Applications include
    modeling trait and niche hypervolumes and species distribution modeling.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

