{% set version = '0.1.3' %}
{% set name = 'colorplaner' %}
{% set hash = 'cfd92dd7bd7c1a5e54002128dd5c13c2a04224f44f1e0bd4618b4ee953991857' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: 'r-{{ name }}'
  version: {{ version }}

source:
  fn: colorplaner_{{ version }}.tar.gz
  url: 'https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz'
  sha256: '{{ hash }}'

build:
  skip: True    # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-digest
    - r-ggplot2 >=2.0.0
    - r-gtable
    - r-scales

  run:
    - r-base
    - r-digest
    - r-ggplot2 >=2.0.0
    - r-gtable
    - r-scales

test:
  commands:
    - $R -e "library('colorplaner')"           # [not win]

about:
  home: 'https://github.com/wmurphyrd/colorplaner'
  license: 'GPL-2'
  license_family: 'GPL2'
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A "ggplot2" Extension to Visualize Two Variables per Color Aesthetic Through Color Space Projection.'
  description: |
    'With this technique for 2-D color mapping, one can
    create a bivariate choropleth in R as well as other visualizations with multivariate
    color scales. Includes two new scales and a new guide for "ggplot2".'

