{% set version = '1.2' %}
{% set name = 'rcdd' %}
{% set hash = '5e910060841ee7a1fcbfbafb189323633ac3f1d753459727f31002ba5d6ef1e8' %}

package:
  name: 'r-{{ name }}'
  version: '{{ version|replace("-", "_") }}'

source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz'
  sha256: '{{ hash }}'

build:
  skip: True  # [win]
  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - pkg-config
    - make

  host:
    - r >=3.0.2
    - gmp

  run:
    - r >=3.0.2
    - gmp

test:
  commands:
    - $R -e "library('rcdd')"

about:
  home: 'http://www.stat.umn.edu/geyer/rcdd/'
  license: 'GPL-2'
  license_family: 'GPL2'
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'rcdd - Computational Geometry - C Double Description'
  Description: |
    'R interface to (some of) cddlib (<http://www.ifor.math.ethz.ch/~fukuda/cdd_home/cdd.html>).
    Converts back and forth between two representations of a convex polytope: as solution
    of a set of linear equalities and inequalities and as convex hull of set of points
    and rays. Also does linear programming and redundant generator elimination (for
    example, convex hull in n dimensions).  All functions can use exact infinite-precision
    rational arithmetic.'

